# -*- coding: utf-8 -*-
"""Shared result limits for Guanlan CLI, MCP, and internal helpers."""

DEFAULT_SEARCH_LIMIT = 50
MAX_SEARCH_LIMIT = 100

DEFAULT_RESEARCH_LIMIT = 50
MAX_RESEARCH_LIMIT = 100

DEFAULT_HOTNEWS_LIMIT = 50
MAX_HOTNEWS_LIMIT = 100
MAX_HOTNEWS_PER_SOURCE_LIMIT = 25

DEFAULT_READ_FALLBACK_LIMIT = 20
MAX_READ_FALLBACK_LIMIT = 20

DEFAULT_ARCHIVE_SEARCH_LIMIT = 50
DEFAULT_ARCHIVE_LIST_LIMIT = 50
MAX_ARCHIVE_SEARCH_LIMIT = 100

DEFAULT_PULSE_LIMIT = 50
MAX_PULSE_LIMIT = 100
