# -*- coding: utf-8 -*-
"""Shared result limits for Guanlan CLI, MCP, and internal helpers."""

DEFAULT_SEARCH_LIMIT = 80
MAX_SEARCH_LIMIT = 100

DEFAULT_RESEARCH_LIMIT = 80
MAX_RESEARCH_LIMIT = 100
DEFAULT_MCP_RESEARCH_READ_TOP = 0
RECOMMENDED_AGENT_RESEARCH_READ_TOP = 2
MAX_MCP_RESEARCH_READ_TOP = 5
MAX_AGENT_RESEARCH_READ_TOP = 5

DEFAULT_HOTNEWS_LIMIT = 80
MAX_HOTNEWS_LIMIT = 100
MAX_HOTNEWS_PER_SOURCE_LIMIT = 25

DEFAULT_READ_FALLBACK_LIMIT = 20
MAX_READ_FALLBACK_LIMIT = 20

DEFAULT_ARCHIVE_SEARCH_LIMIT = 80
DEFAULT_ARCHIVE_LIST_LIMIT = 80
MAX_ARCHIVE_SEARCH_LIMIT = 100

DEFAULT_PULSE_LIMIT = 80
MAX_PULSE_LIMIT = 100

DEFAULT_FEEDS_LIMIT = 80
MAX_FEEDS_LIMIT = 100
